name: CI

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Install
        run: yarn
      - name: Jest
        run: yarn test
      - name: Build
        run: yarn build
      - name: Update version
        run: node ./scripts/update.js
      - name: Commit version change
        run: |
          git config user.name jiangzj1008
          git config user.email jiangzj1008@outlook.com
          git add .
          git commit -m "feat: update version"
          git push
      # - name: Publish
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
